### ISSUE TITLE
Using Vue

### ISSUE THREAD

**Issue by ewarrin** [jack-pallot/dogpatch#1]
Hey great theme. I am trying to integrate Vue. Not a total noob but far from a pro. Here is what I have been trying:

Here is my App.js

```
import Vue from 'vue';
import Example from './components/Example';

new Vue({
  el: '#js-app',
  components: {
    Example, 
  },
});
```

Here is my Example.vue

```
<template>
   <div>
      Hello World
   </div>
</template>

<script>
export default {

}
</script>
```

It shows the "Hello World" in my page but doesnt load any scripts after that. 

Here is the error it gives me

- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

Any idea of what could be happening? Thanks for your help.

**Comment by ewarrin** [comment]
Had an unclosed `<div>` tag, it works now, sorry.

**Comment by jack-pallot** [comment]
Glad you've sorted it.

Another time this can happen is when <script> tags are placed within the `<div id="js-app"></div>` container. WordPress can be a nightmare for this, depending on what plugins you're using. You can always set the container to not wrap the whole site, or re-init Vue on an individual sections instead of the whole page.

```
new Vue({
  el: '#js-profile-component',
});

```
```
new Vue({
  el: '#js-navigation-component',
});

```
Also, if you ever need to include some scripts that aren't Vue, like a third-party lib, you can either enqueue it, or create a new partial in /partials and use this function to move whatever JS to the footer. That way the script will only be included if that partial is included on the page.

```
<?php function movePartialScriptsToFooter() { ?>
  <script src="/wp-content/themes/dogpatch/dist/js/myscript.js"></script>
<?php } add_action('wp_footer', 'movePartialScriptsToFooter', 20); ?>
```
